### ISSUE TITLE
Default texture in advancement tab

### ISSUE THREAD

**Issue by VillarosaKeebs** [AntoninHuaut/TropicalFish#3]
I installed the Data pack to my server, I also installed the texture pack. It seems that the data pack works fine except the tabs are not all side by side with each other but instead mixed in. Not a big deal there. But the texture ack does not seem to work on version 1.19.3 so every fish in the advancements just has the default tropical fish texture. Not sure if this is because I don't have optifine but instead a mix of different mods since optifabric hasn't been updated to 1.19.3 or something but if the pack could be updated to fix this on 1.19.3 that would be great since my friends are obsessed with catching fish

**Comment by AntoninHuaut** [comment]
Hi, I just did the development to generate the pack, on the technical side, I'll let you contact: https://www.curseforge.com/members/eclairdefeu360

**Comment by VillarosaKeebs** [comment]
Ok thanks I will try and message them

**Comment by AntoninHuaut** [comment]
> Ok thanks I will try and message them

Okay, I talked to him, I made the changes. The links on curseforge have been updated, can you tell me if the changes fix the problem?
