### ISSUE TITLE
Black fish

### ISSUE THREAD

**Issue by zer0p1us** [AntoninHuaut/TropicalFish#5]
Since 1.19.3 blacked colored fish have been able to spawn, [bug tracker](bugs.mojang.com/browse/MC-261096), I've made a fork to enable the black fish tracking but notice the black fish textures missing. I presume the texture were procedurally generated, I was wondering if you might have already made them and be able to share them or would be able to share the method used to generate them in the first place?

**Comment by AntoninHuaut** [comment]
Hi, I will check with the person who generated the texture.

**Comment by EclairDeFeu360** [comment]
Hi, I've generated the textures, they just need to be cropped and resized, I'll do that tomorrow. Originally someone had prepared the textures and colour palettes. Some of the textures were done by hand and some were generated by someone else, but the result was very buggy. So this time I generated the textures using VBScript and the Isometric Renders mod.

**Comment by EclairDeFeu360** [comment]
Here you go
[black_tropical_fish.zip](https://github.com/AntoninHuaut/TropicalFish/files/13400453/black_tropical_fish.zip)

**Comment by zer0p1us** [comment]
Cheers mate 👍
